### ISSUE TITLE
What about QtJambi?

### ISSUE THREAD

**Issue by brotenet** [swt-initiative31/documents#9]
Hi all,

_Just adding a suggestion here that may be of worth looking into:_

What about looking into QtJambi?
It's a QT based framework which is quite extensive, fast, has ARM (on Android) support and a clean modular structure (https://github.com/OmixVisualization/qtjambi/blob/v6.8.0/www/Modules.md)

While it is architecture dependent, self contained .jar builds having only the modules needed can be produced that may be capable for supporting the SWT API.

I've played with it from time-to time (but not professionally) and it is a quite stable project and the repository is active as well.
The license is GPL v3 for the bindings but I don't know if this extends also to the underlying native Qt libraries. 

[https://github.com/OmixVisualization/qtjambi](https://github.com/OmixVisualization/qtjambi)

**Comment by HeikoKlare** [comment]
Thank you for that pointer! Unfortunately, GPL is not a fitting license, which is also the reason why we did not investigate Qt as a potential framework in general. Qt is also licensed under LGPL for some time now, which could be fitting under specific conditions, but since there is no guarantee for continued LGPL-licensed releases of Qt, the risk is too high to consider it as a technology candidate.
